version: '3'

services:
  app:
    build:
      context: ./
    container_name: cloud_storage_app
    ports:
      - "8000:80"
    depends_on:
      - postgres
    env_file:
      - .env
    restart: always
    networks:
      default:

  postgres:
    image: postgres:16.2
    container_name: cloud_storage_db
    restart: always
    env_file:
      - .env
    networks:
      default:
